name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-alpine
    steps:
    - uses: actions/checkout@v2
    - run: apk add build-base
    - run: go test -v
